# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bW8qWH6EOjCGv8VyzRl-k0qj0UkpkpNv
"""

print("Hello World")

print("Welcome")